[build]
  command = "npm install && npm run build"
  publish = ".next"  # Cambiado a .next para Next.js

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# [[redirects]]  # Comentado o eliminado
#   from = "/*"
#   to = "/index.html"
#   status = 200

# [functions]  # Comentado o eliminado si no lo usas
#   directory = "functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; font-src 'self';"